name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22

    - name: Build and Test Apps
      run: ./do-app.sh

    - name: Test Libraries
      run: ./do-libs.sh

    - name: Acceptance Test [with some real data]
      run: ./do-hamlet.sh
